[tools]
# Languages
node = "lts"
python = "latest"
go = "latest"

# CLI tools
eza = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
bat = "latest"
starship = "latest"
bun = "latest"

[settings]
activate_aggressive = true
